runtime: python27
api_version: 1
threadsafe: yes

env_variables:
    CLOUDSQL_CONNECTION_NAME: ajjohnso-aware
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: Oink0ink
    
handlers:
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"